REVOKE ALL ON AUCTION FROM aicim;
REVOKE ALL ON MOUVEMENT FROM aicim;
REVOKE ALL ON USERS FROM aicim;
REVOKE ALL ON DATATION FROM aicim;

-- GRANT CONNECT TO aicim;

GRANT EXECUTE ON check_user TO aicim;
--GRANT EXECUTE ANY PROCEDURE TO aicim;